export const users = [
  {
    id: 1,
    userName: "Leon",
    firstName: "Leon",
    lastName: "Matis",
    fullName: "Leon Matis",
    lastLogin: "07.02.2022",
    enabled: true,
  },
  {
    id: 2,
    userName: "Bryan",
    firstName: "Bryan",
    lastName: "Sanchez",
    fullName: "Bryan Sanchez",
    lastLogin: "05.02.2022",
    enabled: false,
  },
  {
    id: 3,
    userName: "Kenley",
    firstName: "Kenley",
    lastName: "Anderson",
    fullName: "Kenley Anderson",
    lastLogin: "01.02.2022",
    enabled: true,
  },
  {
    id: 4,
    userName: "Oriana",
    firstName: "Oriana",
    lastName: "Price",
    fullName: "Oriana Price",
    lastLogin: "20.01.2022",
    enabled: true,
  },
  {
    id: 5,
    userName: "Gabrielle",
    firstName: "Gabrielle",
    lastName: "Ross",
    fullName: "Gabrielle Ross",
    lastLogin: "10.01.2022",
    enabled: false,
  },
  {
    id: 6,
    userName: "qwe",
    firstName: "qwe",
    lastName: "qwe",
    fullName: "qwe qwe",
    lastLogin: "10.01.2022",
    enabled: null,
  },
];
